#
# Module manifest for module 'SvnModule'
#
# Generated by: Seth Wright
#
# Generated on: 8/12/2010
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = ''

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'f5e14cf0-5e2c-4641-a507-da4b82636a6f'

# Author of this module
Author = 'Seth Wright'

# Company or vendor of this module
CompanyName = 'James Madison University'

# Copyright statement for this module
Copyright = 'Copyright © 2011 Seth Wright <wrightst@jmu.edu>'

# Description of the functionality provided by this module
Description = 'Functions related to managing Microsoft Exchange'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules = 'UserProvisioning.psm1',
                'Expand-DistributionGroup.psm1',
                'Get-RedirectRuleInformation.psm1',
                'RemoteConections.psm1',
                'Get-ExchangeReplicationInfo.psm1',
                'Get-MailboxDatabaseStatistics.psm1',
                'Add-ResourceDelegate.psm1',
                'Remove-ResourceDelegate.psm1',
                'EmailTemplateFunctions.psm1',
                'Get-ActiveSyncStatistics.psm1',
                'Get-SmtpLogs.psm1',
                'DelegateListLink.psm1',
                'Get-MessageLatencyStatistics.psm1'

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList =    'UserProvisioning.psm1',
                'Expand-DistributionGroup.psm1',
                'Get-RedirectRuleInformation.psm1',
                'RemoteConections.psm1',
                'Get-ExchangeReplicationInfo.psm1',
                'Get-MailboxDatabaseStatistics.psm1',
                'Add-ResourceDelegate.psm1',
                'Remove-ResourceDelegate.psm1',
                'EmailTemplateFunctions.psm1',
                'Get-ActiveSyncStatistics.psm1',
                'Get-SmtpLogs.psm1',
                'DelegateListLink.psm1',
                'Get-MessageLatencyStatistics.psm1'

# List of all files packaged with this module
FileList =      'UserProvisioning.psm1',
                'Expand-DistributionGroup.psm1',
                'Get-RedirectRuleInformation.psm1',
                'RemoteConections.psm1',
                'Get-ExchangeReplicationInfo.psm1',
                'Get-MailboxDatabaseStatistics.psm1',
                'Add-ResourceDelegate.psm1',
                'Remove-ResourceDelegate.psm1',
                'EmailTemplateFunctions.psm1',
                'Get-ActiveSyncStatistics.psm1',
                'Get-SmtpLogs.psm1',
                'DelegateListLink.psm1',
                'Get-MessageLatencyStatistics.psm1'

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''

}

